apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: production
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE IF NOT EXISTS mytable (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50) NOT NULL
    );
    INSERT INTO mytable (name) VALUES ('Item 1'), ('Item 2'), ('Item 3');