version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://backend:8000/api/items
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - ALLOWED_ORIGINS=http://frontend:80
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=root
      - DB_PASSWORD=password
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # <-- CRUCIAL CHANGE HERE

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:  # <-- HEALTHCHECK ADDED
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: