apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
type: Opaque
data:
  db-user: cm9vdA==  # base64 encoded "root"
  db-password: cGFzc3dvcmQ=  # base64 encoded "password"